name: Check_PR

on:
  pull_request:
    branches: [main]
jobs:
  Check:
    name: Lint & Unit Tests Check
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Set work folder permissions
        run: pwd && sudo chown -R $USER:$USER ./
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        run: | 
          git config --global url.https://github.com/.insteadOf git@github.com:
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn
      - name: Run linter
        run: yarn lint
      - name: Run unit tests
        run: yarn test
